services:
  database:
    image: "mysql:8.2.0"
    container_name: assembleia_mysql_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-mysql-assembleia:/var/lib/mysql

  validator-fiscal-app:
    image: diegoneves/validator-fiscal:latest
    container_name: validator_fiscal_api
    ports:
      - "8001:8001"

volumes:
  db-mysql-assembleia:
