server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  api:
    url:
      validator-fiscal: http://${FISCAL_HOST}:${FISCAL_PORT}/v1/usuario/associado/

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
    springframework:
      security: DEBUG
